package com.vasiliyrogozhin85.posp.host;
import android.content.*;import android.provider.MediaStore;import java.io.*;import java.text.*;import java.util.*;import java.util.zip.*;
public final class ResearchStore{
 private final Context c; public final File root; private final File missing;
 public ResearchStore(Context c)throws IOException{this.c=c;File b=c.getExternalFilesDir(null);if(b==null)b=c.getFilesDir();root=new File(b,"research/session_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date()));if(!root.mkdirs()&&!root.isDirectory())throw new IOException("Cannot create research dir");missing=new File(root,"missing_data.txt");}
 public synchronized void text(String rel,String data)throws IOException{File f=new File(root,rel);File p=f.getParentFile();if(p!=null)p.mkdirs();try(FileOutputStream o=new FileOutputStream(f)){o.write(data.getBytes("UTF-8"));}}
 public synchronized void missing(String what,String why){try(FileWriter w=new FileWriter(missing,true)){w.write(what+" | "+why+"\n");}catch(Exception ignored){}}
 public File zip()throws IOException{File z=new File(root.getParentFile(),"POSP_OS_Research_Bundle_"+System.currentTimeMillis()+".zip");try(ZipOutputStream out=new ZipOutputStream(new FileOutputStream(z))){add(out,root,root);}return z;}
 private void add(ZipOutputStream z,File base,File f)throws IOException{File[] ls=f.listFiles();if(f.isDirectory()){if(ls!=null)for(File x:ls)add(z,base,x);return;}String n=base.toURI().relativize(f.toURI()).getPath();z.putNextEntry(new ZipEntry(n));try(FileInputStream in=new FileInputStream(f)){byte[]b=new byte[16384];int k;while((k=in.read(b))>0)z.write(b,0,k);}z.closeEntry();}
 public String exportZip()throws IOException{File z=zip();ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,z.getName());v.put(MediaStore.Downloads.MIME_TYPE,"application/zip");v.put(MediaStore.Downloads.RELATIVE_PATH,"Download/POSPReports");android.net.Uri u=c.getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new IOException("MediaStore insert failed");try(InputStream in=new FileInputStream(z);OutputStream out=c.getContentResolver().openOutputStream(u)){byte[]b=new byte[16384];int n;while((n=in.read(b))>0)out.write(b,0,n);}return "Download/POSPReports/"+z.getName();}
}
