plugins {
    id "com.android.application"
}

android {
    namespace "com.vasiliyrogozhin85.posp.host"
    compileSdk 36

    defaultConfig {
        applicationId "com.vasiliyrogozhin85.posp.host"
        minSdk 26
        targetSdk 36
        versionCode 8
        versionName "0.8"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(":common")
}
