plugins { id "com.android.application" }
android {
    namespace "com.vasiliyrogozhin85.posp.client"
    compileSdk 36
    defaultConfig {
        applicationId "com.vasiliyrogozhin85.posp.client"
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName "0.3"
    }
    signingConfigs {
        pospDev {
            storeFile file("signing/posp-client-dev.jks")
            storePassword "pospclient2026"
            keyAlias "pospclientdev"
            keyPassword "pospclient2026"
        }
    }
    buildTypes { debug { signingConfig signingConfigs.pospDev } }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { implementation project(":common") }
